/**
 * A small stand-in for `@vipper/iam-connector` (see docs/plan/README.md's "Risks and open
 * assumptions" and the root `.npmrc`): `npm.vipper.network` resolves but 401s without a
 * registry token this repo has no way to obtain, so `pnpm add @vipper/iam-connector` cannot
 * complete here. The connector is itself dependency-free by its own README ("No NestJS, no
 * React, no server dependencies — just native `fetch`"), so this hits the same two documented
 * endpoints directly:
 *
 * - `POST ${apiBase}/oauth/token` — client-credentials grant for THIS server's own bearer.
 * - `POST ${apiBase}/oauth/introspect` — RFC 7662 introspection, presenting that bearer.
 * - `POST ${apiBase}/authorize` — allow/deny, presenting the END USER's bearer instead.
 *
 * The two bearers are different on purpose and it matters: introspection asks vipper.iam "who
 * is this token?" and is a guarded call THIS server makes as itself, while `/authorize` is
 * deliberately unguarded and judges whatever credential is presented to it. Sending the wrong
 * one on either route fails in a way that looks like a configuration problem rather than a
 * protocol one.
 *
 * Both calls speak the identical wire contract the real connector would, so nothing downstream
 * of {@link IamAuthGuard} needs to know which of the two is live. Swapping this for
 * `@vipper/iam-connector` later, once the registry token is available, only touches
 * `iam.module.ts`'s provider factory.
 */

export interface IamClientConfig {
  /** The IAM REST API base, e.g. `https://auth.vipper.network/api/v1` (trailing slash optional). */
  apiBase: string;
  /**
   * This resource server's own SERVICE ACCOUNT credentials, exchanged for a bearer token at
   * `/oauth/token`. `clientId` is generated by vipper.iam when the service account is created
   * (it looks like `svc_…`) and cannot be chosen — a guessed value fails the grant with
   * `invalid_client`.
   */
  clientId: string;
  clientSecret: string;
  /** Optional fetch override, for tests. Defaults to the platform's global `fetch`. */
  fetch?: typeof fetch;
}

export interface AuthorizeInput {
  /** The credential being authorized — presented as the bearer on `/authorize`. */
  token: string;
  resourceType: string;
  identifier: string;
  action: string;
}

export interface AuthorizeResult {
  allowed: boolean;
  scopes: string[];
}

export interface IntrospectionResult {
  active: boolean;
  subject: string | null;
  subjectType: 'user' | 'service' | null;
  scopes: string[];
  audience: string | null;
}

export interface IamClient {
  introspectToken(token: string): Promise<IntrospectionResult>;
  authorize(input: AuthorizeInput): Promise<AuthorizeResult>;
}

export function createIamClient(config: IamClientConfig): IamClient {
  const apiBase = config.apiBase.replace(/\/+$/, '');
  const doFetch = config.fetch ?? globalThis.fetch;
  if (typeof doFetch !== 'function') {
    throw new Error('iam client: no fetch implementation available; pass `fetch` in the config.');
  }
  /**
   * This server's OWN access token, minted from its service-account credentials and reused
   * until shortly before it expires.
   *
   * This used to send HTTP Basic on `/oauth/introspect`, on the reasoning that RFC 7662 lets
   * the caller authenticate that way. vipper.iam does not: that route sits behind its
   * `OidcAuthGuard`, whose own docstring says "the CALLER proves who it is with its own bearer
   * token/PAT". Basic is not a bearer, so every single request came back
   *
   *   401 {"message":"Missing bearer token"}
   *
   * which `introspectToken` turns into a thrown error, so the mirror API answered 500 to every
   * poll and not one sync ever reached the database. The connector's documented flow — and now
   * this one — is to exchange the credentials at `POST ${apiBase}/oauth/token` for a
   * short-lived JWT and present that.
   */
  let cachedToken: { value: string; expiresAt: number } | null = null;

  async function serviceToken(): Promise<string> {
    // 30s of headroom, so a token cannot expire in flight between here and the call that uses it.
    if (cachedToken && cachedToken.expiresAt - 30_000 > Date.now()) return cachedToken.value;

    const res = await doFetch(`${apiBase}/oauth/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        grant_type: 'client_credentials',
        client_id: config.clientId,
        client_secret: config.clientSecret,
      }).toString(),
    });
    if (!res.ok) {
      // `invalid_client` here means the id/secret pair is wrong — the service account's client
      // id is GENERATED by vipper.iam (it looks like `svc_…`), never chosen by the caller.
      throw new Error(
        `iam client: client-credentials grant failed (${res.status} ${await safeText(res)})`,
      );
    }
    const json = (await res.json()) as { access_token: string; expires_in: number };
    cachedToken = {
      value: json.access_token,
      expiresAt: Date.now() + json.expires_in * 1000,
    };
    return cachedToken.value;
  }

  async function introspectToken(token: string): Promise<IntrospectionResult> {
    const res = await doFetch(`${apiBase}/oauth/introspect`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${await serviceToken()}`,
      },
      body: JSON.stringify({ token }),
    });
    if (!res.ok) {
      throw new Error(`iam client: introspection failed (${res.status} ${await safeText(res)})`);
    }
    const json = (await res.json()) as {
      active: boolean;
      sub?: string;
      scope?: string;
      aud?: string;
      sub_type?: 'user' | 'service';
    };
    return {
      active: json.active,
      subject: json.sub ?? null,
      subjectType: json.sub_type ?? null,
      scopes: json.scope ? json.scope.split(' ').filter(Boolean) : [],
      audience: json.aud ?? null,
    };
  }

  async function authorize(input: AuthorizeInput): Promise<AuthorizeResult> {
    const res = await doFetch(`${apiBase}/authorize`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        // The credential BEING authorized is presented here — not this resource server's own.
        Authorization: `Bearer ${input.token}`,
      },
      body: JSON.stringify({
        resourceType: input.resourceType,
        identifier: input.identifier,
        action: input.action,
      }),
    });
    if (!res.ok) {
      throw new Error(`iam client: authorize failed (${res.status} ${await safeText(res)})`);
    }
    return (await res.json()) as AuthorizeResult;
  }

  return { introspectToken, authorize };
}

/** Read a response body as text without throwing (for error messages). */
async function safeText(res: Response): Promise<string> {
  try {
    return await res.text();
  } catch {
    return '';
  }
}
