/**
 * Tests for the pure half of session discovery (Phase 8 B2).
 *
 * The encoding and the transcript shape are UNDOCUMENTED CLI conventions, so the
 * fixtures below are copied from real files under `~/.claude/projects` rather than
 * invented. They run under Vitest with no filesystem and no `claude` binary; the
 * reader in `listClaudeSessions` is deliberately not tested here, because pointing
 * it at a fake home directory would only assert that `readdir` works.
 */
import { describe, expect, it } from 'vitest';
import { encodeProjectDir, parseSessionPreview } from './claudeSessions';

describe('encodeProjectDir', () => {
  it('encodes a Windows path the way the CLI stores it', () => {
    // Verified against the real folder for this repo: the colon and both
    // separators each become a hyphen, which is why "C:" gains two.
    expect(encodeProjectDir('C:\\Repositories\\task-manager')).toBe('C--Repositories-task-manager');
  });

  it('encodes a POSIX path, leading separator included', () => {
    expect(encodeProjectDir('/home/me/app')).toBe('-home-me-app');
  });

  it('leaves an existing hyphen alone', () => {
    expect(encodeProjectDir('task-manager')).toBe('task-manager');
  });

  it('preserves case and digits', () => {
    expect(encodeProjectDir('C:\\Repos\\App2')).toBe('C--Repos-App2');
  });

  it('replaces dots, spaces and every other punctuation mark', () => {
    expect(encodeProjectDir('/srv/my app/.config/v1.2')).toBe('-srv-my-app--config-v1-2');
  });

  it('encodes a trailing separator as its own hyphen', () => {
    expect(encodeProjectDir('C:\\Repos\\')).toBe('C--Repos-');
  });

  it('has nothing to say about an empty path', () => {
    expect(encodeProjectDir('')).toBe('');
  });
});

/** A transcript line, in the shape the CLI writes. */
function userLine(content: unknown, extra: Record<string, unknown> = {}): string {
  return JSON.stringify({
    parentUuid: null,
    isSidechain: false,
    type: 'user',
    message: { role: 'user', content },
    timestamp: '2026-07-29T05:35:03.954Z',
    ...extra,
  });
}

describe('parseSessionPreview', () => {
  it('takes the first typed prompt and the first timestamp', () => {
    const head = [
      // The opening entries carry no timestamp at all.
      JSON.stringify({ type: 'mode', mode: 'normal', sessionId: 'abc' }),
      JSON.stringify({
        type: 'file-history-snapshot',
        snapshot: { timestamp: '2026-07-29T05:35:03.956Z' },
      }),
      userLine('whats the status of this project'),
    ].join('\n');

    expect(parseSessionPreview(head)).toEqual({
      startedAt: '2026-07-29T05:35:03.954Z',
      preview: 'whats the status of this project',
    });
  });

  it('reads a prompt that arrived as text blocks', () => {
    const head = userLine([
      { type: 'image', source: {} },
      { type: 'text', text: 'fix the board' },
    ]);
    expect(parseSessionPreview(head).preview).toBe('fix the board');
  });

  it('skips tool results, which are user entries too', () => {
    const head = [
      userLine([{ type: 'tool_result', tool_use_id: 'toolu_1', content: 'a file listing' }]),
      userLine('the real prompt'),
    ].join('\n');
    expect(parseSessionPreview(head).preview).toBe('the real prompt');
  });

  it("skips a subagent's turn — its prompt is ours, not the user's", () => {
    const head = [
      userLine('go and explore the repo', { isSidechain: true }),
      userLine('what changed?'),
    ].join('\n');
    expect(parseSessionPreview(head).preview).toBe('what changed?');
  });

  it('skips slash-command plumbing and echoed shell output', () => {
    const head = [
      userLine('<command-name>/loop</command-name>'),
      userLine('<local-command-stdout>ok</local-command-stdout>'),
      userLine(
        'Caveat: The messages below were generated by the user while running local commands',
      ),
      userLine('release it'),
    ].join('\n');
    expect(parseSessionPreview(head).preview).toBe('release it');
  });

  it('strips injected context and skips an entry that was nothing else', () => {
    const head = [
      userLine('<system-reminder>background note</system-reminder>'),
      userLine('<system-reminder>note</system-reminder>\n\nactual question'),
    ].join('\n');
    expect(parseSessionPreview(head).preview).toBe('actual question');
  });

  it('skips meta entries', () => {
    const head = [userLine('injected', { isMeta: true }), userLine('typed')].join('\n');
    expect(parseSessionPreview(head).preview).toBe('typed');
  });

  it('collapses a multi-line prompt onto one line', () => {
    expect(parseSessionPreview(userLine('push,\n\n  then   release')).preview).toBe(
      'push, then release',
    );
  });

  it('ellipsizes a long prompt', () => {
    const { preview } = parseSessionPreview(userLine('x'.repeat(500)));
    expect(preview).toHaveLength(140);
    expect(preview.endsWith('…')).toBe(true);
  });

  it('tolerates a truncated or malformed line rather than throwing', () => {
    const head = ['{"type":"user","message":{"content":"half a li', 'not json at all', ''].join(
      '\n',
    );
    expect(parseSessionPreview(head)).toEqual({ startedAt: null, preview: '' });
  });

  it('reports nothing for an empty transcript', () => {
    expect(parseSessionPreview('')).toEqual({ startedAt: null, preview: '' });
  });

  it('still reports a start time when no human prompt is readable', () => {
    const head = JSON.stringify({ type: 'assistant', timestamp: '2026-07-29T05:35:03.954Z' });
    expect(parseSessionPreview(head)).toEqual({
      startedAt: '2026-07-29T05:35:03.954Z',
      preview: '',
    });
  });
});
