/**
 * Discovering the Claude conversations that already exist for a directory
 * (Phase 8, Deliverable B2).
 *
 * The CLI keeps every conversation as a JSON-lines transcript under
 * `~/.claude/projects/<encoded-cwd>/<session-id>.jsonl`, where the filename is
 * exactly the id `claude --resume` wants. Listing that directory turns "attach an
 * existing session" from a paste-a-UUID chore into a pick-list.
 *
 * THIS LAYOUT IS AN UNDOCUMENTED CLI CONVENTION. It was verified against the
 * install on this machine and nothing more, so every step here fails soft: a
 * missing directory, an unreadable file, a renamed field or a shape we have never
 * seen produces a shorter list (or an empty one), never an exception. The manual
 * paste path in the UI is the contract; this is a convenience on top of it, and
 * the app must keep working the day the CLI changes its mind.
 *
 * Pure parsing lives in `encodeProjectDir` / `parseSessionPreview` so it can be
 * unit-tested without a filesystem; only `listClaudeSessions` touches disk.
 */
import { open, readdir, stat } from 'node:fs/promises';
import type { ClaudeSessionSummary } from '@shared/ipc';
import { hostJoin, localHost, type ExecHost } from './exec';

/** A transcript filename is the session id: the UUID `claude --resume` takes. */
const SESSION_ID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * How much of a transcript we read to find its opening prompt.
 *
 * Generous, but not unbounded: a prompt with a pasted image inlines the image on
 * the same line, which runs to hundreds of kilobytes. Such a session lists with an
 * empty preview rather than costing megabytes to describe — the id and the dates
 * still identify it, and no size of head would win against a multi-megabyte image.
 */
const HEAD_BYTES = 128 * 1024;

/** Longest preview we hand to the UI; the rest is ellipsized. */
const PREVIEW_CHARS = 140;

/**
 * The directory name the CLI derives from a working directory.
 *
 * Every character that is not a letter or a digit becomes a hyphen — so
 * `C:\Repositories\task-manager` is stored as `C--Repositories-task-manager`
 * (the colon and both separators each contribute one hyphen) and `/home/me/app`
 * as `-home-me-app`. The mapping is lossy and NOT reversible, which is fine: we
 * only ever go from a known cwd to its folder.
 *
 * The cwd must be given in the shape of the host that ran the CLI — a WSL
 * project's path is a Linux path, and encoding its Windows spelling would look
 * up a folder that does not exist.
 */
export function encodeProjectDir(cwd: string): string {
  return cwd.replace(/[^a-zA-Z0-9]/g, '-');
}

/** What a transcript's opening lines tell us about the conversation. */
export interface SessionPreview {
  /** ISO timestamp of the first entry that carries one, or null if none does. */
  startedAt: string | null;
  /** The first human prompt, collapsed to one line. Empty when none was found. */
  preview: string;
}

/**
 * Wrappers the CLI writes as `user` entries that were never typed by a human:
 * slash-command plumbing, shell output echoed back, and the banner it prepends
 * after a local command. Showing any of these as "the prompt" would be a lie.
 */
const SYNTHETIC_PREFIXES = [
  '<command-name>',
  '<command-message>',
  '<command-args>',
  '<local-command-stdout>',
  '<local-command-stderr>',
  '<bash-input>',
  '<bash-stdout>',
  '<user-memory-input>',
  'Caveat: The messages below were generated by the user while running local commands',
];

/** Injected context, not part of what the user typed. */
const SYSTEM_REMINDER_RE = /<system-reminder>[\s\S]*?<\/system-reminder>/g;

/**
 * Pull the text a human actually typed out of one `user` entry, or null if this
 * entry is not one: a tool result, a subagent's turn, CLI plumbing, or a shape
 * we do not recognize.
 */
function humanText(entry: Record<string, unknown>): string | null {
  if (entry.type !== 'user') return null;
  // A sidechain is a subagent's conversation; its prompt is ours, not the user's.
  if (entry.isSidechain === true || entry.isMeta === true) return null;

  const message = entry.message as { content?: unknown } | undefined;
  const content = message?.content;

  let text: string | null = null;
  if (typeof content === 'string') {
    text = content;
  } else if (Array.isArray(content)) {
    // A typed prompt with attachments arrives as blocks; a tool result arrives as
    // blocks too, so take text and ignore everything else.
    for (const block of content) {
      const b = block as { type?: unknown; text?: unknown };
      if (b?.type === 'text' && typeof b.text === 'string') {
        text = b.text;
        break;
      }
    }
  }
  if (text === null) return null;

  const cleaned = text.replace(SYSTEM_REMINDER_RE, '').trim();
  if (!cleaned) return null;
  if (SYNTHETIC_PREFIXES.some((prefix) => cleaned.startsWith(prefix))) return null;
  return cleaned;
}

/**
 * Read the head of a transcript for its start time and opening prompt.
 *
 * Takes text rather than a path so it stays pure and testable. Unparsable lines
 * are skipped rather than fatal — the head may end mid-line, and a future CLI
 * may write entries we know nothing about.
 */
export function parseSessionPreview(head: string): SessionPreview {
  let startedAt: string | null = null;
  let preview = '';

  for (const line of head.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    let entry: Record<string, unknown>;
    try {
      entry = JSON.parse(trimmed) as Record<string, unknown>;
    } catch {
      continue;
    }
    if (typeof entry !== 'object' || entry === null) continue;

    if (startedAt === null && typeof entry.timestamp === 'string') {
      startedAt = entry.timestamp;
    }
    if (!preview) {
      const text = humanText(entry);
      if (text) preview = collapse(text);
    }
    if (startedAt !== null && preview) break;
  }

  return { startedAt, preview };
}

/** One line, no runs of whitespace, ellipsized to something a row can hold. */
function collapse(text: string): string {
  const flat = text.replace(/\s+/g, ' ').trim();
  return flat.length > PREVIEW_CHARS ? `${flat.slice(0, PREVIEW_CHARS - 1)}…` : flat;
}

/**
 * Read the first `HEAD_BYTES` of a file as text. Returns '' on any failure.
 *
 * Transcripts run to megabytes and we only need their opening entries, so we
 * deliberately do not read them whole — a project with fifty conversations would
 * otherwise pull a hundred megabytes through to render one dropdown.
 */
async function readHead(path: string): Promise<string> {
  let handle;
  try {
    handle = await open(path, 'r');
    const buffer = Buffer.alloc(HEAD_BYTES);
    const { bytesRead } = await handle.read(buffer, 0, HEAD_BYTES, 0);
    const text = buffer.subarray(0, bytesRead).toString('utf8');
    // A truncated read almost certainly ends mid-line (and mid-UTF-8-sequence);
    // drop that fragment so the parser never sees half an entry.
    if (bytesRead === HEAD_BYTES) {
      const lastBreak = text.lastIndexOf('\n');
      return lastBreak === -1 ? '' : text.slice(0, lastBreak);
    }
    return text;
  } catch {
    return '';
  } finally {
    await handle?.close().catch(() => {});
  }
}

/**
 * The conversations the CLI has on disk for `cwd`, newest first.
 *
 * `host` is the machine that ran them: a WSL project's transcripts live in that
 * distro's home directory, not the one the window runs in. Never throws — an
 * absent or unreadable `~/.claude/projects` yields an empty list, and the UI
 * falls back to asking for a session id by hand.
 */
export async function listClaudeSessions(
  cwd: string,
  host: ExecHost = localHost(),
): Promise<ClaudeSessionSummary[]> {
  if (!cwd.trim()) return [];

  let dir: string;
  try {
    dir = host.toApp(hostJoin(await host.homeDir(), '.claude', 'projects', encodeProjectDir(cwd)));
  } catch {
    return [];
  }

  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return []; // No conversations here yet, or no such layout on this machine.
  }

  // The directory also holds per-session SUBDIRECTORIES named with the same ids,
  // so match files only — and only ones named like a resumable session.
  const files = entries.filter((entry) => {
    if (!entry.isFile() || !entry.name.endsWith('.jsonl')) return false;
    return SESSION_ID_RE.test(entry.name.slice(0, -'.jsonl'.length));
  });

  const sessions = await Promise.all(
    files.map(async (entry): Promise<ClaudeSessionSummary | null> => {
      const path = hostJoin(dir, entry.name);
      try {
        // The transcript is appended to as the conversation runs, so its mtime is
        // when it was last active — far cheaper than reading to the final entry.
        const { mtime } = await stat(path);
        const { startedAt, preview } = parseSessionPreview(await readHead(path));
        return {
          sessionId: entry.name.slice(0, -'.jsonl'.length),
          startedAt: startedAt ?? mtime.toISOString(),
          lastAt: mtime.toISOString(),
          preview,
        };
      } catch {
        return null; // One unreadable transcript must not lose the others.
      }
    }),
  );

  return sessions
    .filter((session): session is ClaudeSessionSummary => session !== null)
    .sort((a, b) => b.lastAt.localeCompare(a.lastAt));
}
